import { Link } from 'react-router-dom';
import HeroCarousel from '../../components/HeroCarousel/HeroCarousel';
import SolutionCard from '../../components/SolutionCard/SolutionCard';
import IndustryCard from '../../components/IndustryCard/IndustryCard';
import PartnerLogo from '../../components/PartnerLogo/PartnerLogo';
import CTASection from '../../components/CTASection/CTASection';
import Icon from '../../components/Icon';
import { heroSlides, valuePillars, solutions, industries, partners, accompaniment, companyHighlights } from '../../data/homeData';
import { paths } from '../../routes/paths';
export default function Home() {
  return <main id="contenido">
    <HeroCarousel images={heroSlides}><div className="hero-main"><div className="hero-copy"><span className="hero-eyebrow">MENOR RIESGO · MENOR COSTO TOTAL · MAYOR ESTABILIDAD</span><h1>Soluciones láser industriales orientadas a proceso</h1><p>Diseñamos e integramos soluciones láser confiables y repetibles, acompañando cada proyecto desde la definición del proceso metalúrgico hasta su operación continua en planta de producción.</p><div className="button-row"><Link className="button" to={paths.contact}>Hablar con un especialista <span aria-hidden="true">→</span></Link><Link className="button button-outline" to={paths.solutions}>Explorar soluciones</Link></div></div><div className="industrial-panel"><div className="panel-heading"><span>ENFOQUE INDUSTRIAL</span><span>XVR</span></div>{[['PROCESO', 'Definición y validación'], ['INTEGRACIÓN', 'Láser, óptica y automatización'], ['APLICACIÓN', 'Manufactura industrial'], ['ACOMPAÑAMIENTO', 'Continuidad operativa']].map(([label, value]) => <div className="panel-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="panel-bottom">SOLUCIONES ORIENTADAS A PROCESO</div></div></div><div className="hero-facts">{[{ icon: 'globe', title: 'México · EE. UU. · CR', text: 'Presencia e ingeniería multirregional' }, { icon: 'check', title: 'Experiencia técnica', text: 'Especialistas en manufactura láser' }, { icon: 'precision', title: 'Continuidad Operativa', text: 'Repetibilidad en cada proceso' }].map(fact => <div key={fact.title}><span className="fact-icon"><Icon name={fact.icon}/></span><div><strong>{fact.title}</strong><p>{fact.text}</p></div></div>)}</div></HeroCarousel>
    <section className="section value-section"><div className="container"><span className="eyebrow">ENFOQUE CENTRADO EN RESULTADOS</span><h2 className="title-limit">Más que equipos, definimos procesos industriales confiables.</h2><p className="section-intro">XVR actúa como socio tecnológico integral, diseñando e integrando ecosistemas tecnológicos completos en lugar de suministrar maquinaria aislada sin contexto.</p><div className="grid-four value-grid">{valuePillars.map((item, index) => <article className="value-card" key={item.title}><div className="value-icon"><Icon name={item.icon}/><span>0{index + 1}</span></div><h3>{item.title}</h3><p>{item.description}</p><small>{item.caption}</small></article>)}</div></div></section>
    <section className="section solutions-section"><div className="container"><span className="eyebrow">GAMA DE APLICACIONES</span><div className="section-heading"><h2>Soluciones para procesos de manufactura láser</h2><Link className="text-link" to={paths.solutions}>Ver todas las soluciones técnicas →</Link></div><div className="grid-four">{solutions.map(item => <SolutionCard key={item.slug} {...item}/>)}</div></div></section>
    <section id="industrias" className="section industries-section"><div className="container"><span className="eyebrow">SECTORES ESPECIALIZADOS</span><h2 className="title-limit">Tecnología láser para industrias de alta exigencia</h2><p className="section-intro">Adaptamos cada proceso a los requerimientos técnicos, normativos y métricas de cada sector industrial.</p><div className="grid-four">{industries.map(item => <IndustryCard key={item.slug} {...item}/>)}</div></div></section>
    <section id="nosotros" className="section about-section"><div className="container about-grid"><div><span className="eyebrow">QUIÉNES SOMOS</span><h2>Un partner tecnológico para la industria</h2><p className="section-intro">XVR es especialista en procesos láser industriales, con operación en México, Estados Unidos y Costa Rica. Acompañamos a nuestros clientes desde la definición del proceso hasta su operación estable en producción.</p><div className="about-highlights">{companyHighlights.map(item => <div key={item.title}><Icon name={item.icon}/><div><h3>{item.title}</h3><p>{item.description}</p></div></div>)}</div></div><div className="about-visual"><figure><img src="/images/branding/laboratorio-placeholder.svg" alt="Área visual provisional para el laboratorio de aplicaciones XVR" loading="lazy" width="600" height="320"/><figcaption><span>LABORATORIO DE APLICACIONES</span><p>Querétaro, MX · Capacidad de prototipado rápido</p></figcaption></figure><div className="location-grid">{[['MÉXICO', 'HQ & Laboratorio'], ['EE. UU.', 'Soporte Técnico'], ['COSTA RICA', 'MedTech Hub']].map(([country, label]) => <div key={country}><strong>{country}</strong><span>{label}</span></div>)}</div></div></div></section>
    <section className="section partners-section"><div className="container"><span className="eyebrow">ECOSISTEMA TECNOLÓGICO</span><h2>Socios tecnológicos</h2><p className="section-intro">Trabajamos con fabricantes internacionales de primer nivel que forman parte fundamental de las soluciones y proyectos llave en mano que desarrollamos.</p><div className="partners-grid">{partners.map(partner => <PartnerLogo key={partner.name} {...partner}/>)}</div><p className="partners-note">Componentes grado industrial con soporte, refaccionamiento y calibración.</p></div></section>
    <section className="section accompaniment-section"><div className="container"><span className="eyebrow">CONTINUIDAD DE OPERACIÓN</span><h2 className="title-limit">Acompañamiento durante todo el ciclo operativo</h2><p className="section-intro">Aseguramos la disponibilidad operativa y la repetibilidad continua de sus líneas de producción mediante soporte técnico de alto nivel.</p><div className="grid-four">{accompaniment.map(item => <article className="accompaniment-card" key={item.title}><span className="icon-tile"><Icon name={item.icon}/></span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
    <CTASection eyebrow="EVALUACIÓN TÉCNICA" title="¿Tu proceso láser está optimizado o solo está funcionando?" description="Revisemos juntos tu aplicación técnica y encontremos la solución más robusta y rentable para tu línea de producción." primaryButtonLabel="Hablar con un especialista" primaryButtonHref={paths.contact}/>
  </main>;
}
